exclude: ^docs/
default_stages: [ commit ]
fail_fast: false
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-yaml
        files: .*\.(yml|yaml)$
        args: [ --multi ]
        exclude: >
          (?x)^(
            .gitlab-ci.yml
          )$
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.780 # Use the sha / tag you want to point at
  #   hooks:
  #     - id: mypy
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [ --config=black.toml ]
        language_version: python3
